### PR TITLE
fix #263

### LINKED ISSUE #263: LoadStorage Error
Commit hash: c4c7b9acce9b2c510a2bae77b6e99dfcb95f95b2
There is an error when reloading the storage from a saved image. It can be reproduced as follows (the path is masked by hand ***):

The TSL file content:
```
cell Person
{
	int Age;
	string Name;
}
```

 The Program.cs file content:
```
class Program
{
	static void Main(string[] args)
	{
		Console.Write("Type save/load: ");
		var input = Console.ReadLine();
		if (input == "save")
		{
			foreach (var item in Enumerable.Range(0, 100))
			{
				AddPerson(item, "person-" + item);
			}
			Global.LocalStorage.SaveStorage();
		}
		else if (input == "load")
		{
			Global.LocalStorage.LoadStorage();
			Console.ReadLine();
		}
	}

	static void AddPerson(int age, string name)
	{
		Person p = new Person(age, name);
		Global.LocalStorage.SavePerson(p);
	}
}
```

The output on the first run with input 'save':
> Type save/load: save
> [ INFO    ] EchoOnConsole set to ON
> [ INFO    ] Log: changing logging directory to ***\bin\Debug\trinity-log.
> [ INFO    ] Loading Graph Engine Extensions.
> [ INFO    ] Scanning for TSL storage extension.
> [ INFO    ] TSL storage extension loaded.
> [ INFO    ] Scanning for MemoryCloud extensions.
> [ INFO    ] No MemoryCloud extension found.
> [ INFO    ] Scanning for startup tasks.
> [ INFO    ] EventLoop: Starting.
> [ INFO    ] LocalMemoryStorage is initialized in read-write mode
> [ INFO    ] Initializing logging facility
> [ INFO    ] Reading log file.
> [ INFO    ] Write-ahead-log successfully loaded. Recovered 0 records.
> [ INFO    ] Creating write-ahead log file ***\bin\Debug\storage\B\write_ahead_log\primary_storage_log_0.dat
> [ INFO    ] Saving storage to [SLOT A]
> [ INFO    ] Save storage complete, image version = 1.
> [ INFO    ] Creating write-ahead log file ***\bin\Debug\storage\A\write_ahead_log\primary_storage_log_1.dat
> [ INFO    ] Dropping write-ahead-log file ***\bin\Debug\storage\B\write_ahead_log\primary_storage_log_0.dat
> [ INFO    ] Saving cell type signatures.
> Press any key to continue . . .

The output on the second run with input 'load':
> Type save/load: load
> [ INFO    ] EchoOnConsole set to ON
> [ INFO    ] Log: changing logging directory to ***\bin\Debug\trinity-log.
> [ INFO    ] Loading Graph Engine Extensions.
> [ INFO    ] Scanning for TSL storage extension.
> [ INFO    ] TSL storage extension loaded.
> [ INFO    ] Scanning for MemoryCloud extensions.
> [ INFO    ] No MemoryCloud extension found.
> [ INFO    ] Scanning for startup tasks.
> [ INFO    ] EventLoop: Starting.
> [ INFO    ] LocalMemoryStorage is initialized in read-write mode
> [ INFO    ] Initializing logging facility
> [ INFO    ] Creating write-ahead log file ***\bin\Debug\storage\A\write_ahead_log\primary_storage_log_2.dat
> [ INFO    ] Loading storage from [SLOT A]
> [ ERROR   ] Storage signature mismatch on trunk #1.
> [ FATAL   ] Failed to load storage: Image signature mismatch.
> Press any key to continue . . .

Then the program exits with error.

### PR DESCRIPTION
**Pull request by yatli**

### CODE REVIEW

File: src/Trinity.C/include/Trinity/IO/BinaryReader.h [hunk 1]
```diff
@@ -96,7 +96,7 @@ namespace Trinity
             }
             bool Read(char* buffer, int32_t start, int32_t count)
             {
-                return (count == fread(buffer + start, count, 1, fp));
+                return (1 == fread(buffer + start, count, 1, fp));
```
Comment (shaobin) [inline src/Trinity.C/include/Trinity/IO/BinaryReader.h]: The parameter name 'count' is confusing. It may be better to rename it to 'element_size' or just 'size' to be consistent with fread()'s parameter name. For the reference, here is the prototype of fread: size_t fread(void *ptr, size_t size, size_t nmemb, FILE *stream).

Comment (yatli) [reply src/Trinity.C/include/Trinity/IO/BinaryReader.h]: sure, we'd better say `size` instead of `count` -- fool me once

Comment (yatli) [reply src/Trinity.C/include/Trinity/IO/BinaryReader.h]: done.

**Review by shaobin — APPROVED** [review]
